### ISSUE TITLE
Segfault on startup on ARM

### ISSUE THREAD

**Issue by JMare** [mavlink/mavros#822]
### Issue details

Segfault on startup causing mavros_node to die.
Problem is only seen on Raspberry Pi 3, doesn't happen on laptop.

Problem is intermittent, happens approximately 70% of the time when I launch mavros.

I have built with `catkin build --cmake-args -DCMAKE_BUILD_TYPE=Debug` and run with GDB, but the segfault backtrace only shows that the problem occurs in `ld-linux-armhf.so.3` and doesnt show the trace into mavros source.

### MAVROS version and platform

Mavros: 0.21.1 Built from source
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[ x  ] ArduPilot
[  ] PX4

Version: 3.5

### Node logs

```
avionics@avionics:~$ roslaunch mavros apm2.launch fcu_url:=udp://localhost:14560@
... logging to /home/avionics/.ros/log/02c0d100-a0eb-11e7-b5ef-b827eb529962/roslaunch-avionics-6866.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://avionics:44969/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 0.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 0.0
 * /mavros/distance_sensor/rangefinder_pub/field_of_view: 0.0
 * /mavros/distance_sensor/rangefinder_pub/frame_id: lidar
 * /mavros/distance_sensor/rangefinder_pub/id: 0
 * /mavros/distance_sensor/rangefinder_pub/send_tf: False
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/rangefinder_sub/id: 1
 * /mavros/distance_sensor/rangefinder_sub/orientation: PITCH_270
 * /mavros/distance_sensor/rangefinder_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_url: udp://localhost:1...
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: NONE
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [6918]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 02c0d100-a0eb-11e7-b5ef-b827eb529962
process[rosout-1]: started with pid [6945]
started core service [/rosout]
process[mavros-2]: started with pid [6963]
[ INFO] [1506231690.993553537]: FCU URL: udp://localhost:14560@
[ WARN] [1506231690.999617807]: init: message from ASLUAV, MSG-ID 201 ignored! Table has different entry.
[ WARN] [1506231691.001320932]: init: message from autoquad, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1506231691.001619057]: init: message from autoquad, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1506231691.003018641]: init: message from matrixpilot, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1506231691.003286766]: init: message from matrixpilot, MSG-ID 151 ignored! Table has different entry.
[ WARN] [1506231691.003517391]: init: message from matrixpilot, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1506231691.003716089]: init: message from matrixpilot, MSG-ID 153 ignored! Table has different entry.
[ WARN] [1506231691.003914578]: init: message from matrixpilot, MSG-ID 155 ignored! Table has different entry.
[ WARN] [1506231691.004115307]: init: message from matrixpilot, MSG-ID 156 ignored! Table has different entry.
[ WARN] [1506231691.004276297]: init: message from matrixpilot, MSG-ID 157 ignored! Table has different entry.
[ WARN] [1506231691.004421974]: init: message from matrixpilot, MSG-ID 158 ignored! Table has different entry.
[ WARN] [1506231691.004576922]: init: message from matrixpilot, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1506231691.004662807]: init: message from matrixpilot, MSG-ID 171 ignored! Table has different entry.
[ WARN] [1506231691.004848953]: init: message from matrixpilot, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1506231691.005042547]: init: message from matrixpilot, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1506231691.005142287]: init: message from matrixpilot, MSG-ID 174 ignored! Table has different entry.
[ WARN] [1506231691.005407912]: init: message from matrixpilot, MSG-ID 175 ignored! Table has different entry.
[ WARN] [1506231691.005590985]: init: message from matrixpilot, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1506231691.005764630]: init: message from matrixpilot, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1506231691.005938328]: init: message from matrixpilot, MSG-ID 178 ignored! Table has different entry.
[ WARN] [1506231691.006119474]: init: message from matrixpilot, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1506231691.006295255]: init: message from matrixpilot, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1506231691.006461557]: init: message from matrixpilot, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1506231691.006638693]: init: message from matrixpilot, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1506231691.006823120]: init: message from matrixpilot, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1506231691.006997755]: init: message from matrixpilot, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1506231691.007178380]: init: message from matrixpilot, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1506231691.007356974]: init: message from matrixpilot, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1506231691.008754266]: init: message from paparazzi, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1506231691.008944005]: init: message from paparazzi, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1506231691.009099162]: init: message from paparazzi, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1506231691.009189995]: init: message from paparazzi, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1506231691.009572287]: init: message from paparazzi, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1506231691.010971557]: init: message from slugs, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1506231691.011165672]: init: message from slugs, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1506231691.011313693]: init: message from slugs, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1506231691.011402703]: init: message from slugs, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1506231691.011582860]: init: message from slugs, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1506231691.011765516]: init: message from slugs, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1506231691.011962182]: init: message from slugs, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1506231691.012156453]: init: message from slugs, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1506231691.012319839]: init: message from slugs, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1506231691.012485568]: init: message from slugs, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1506231691.012656453]: init: message from slugs, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1506231691.012822391]: init: message from slugs, MSG-ID 188 ignored! Table has different entry.
[ WARN] [1506231691.013035151]: init: message from slugs, MSG-ID 191 ignored! Table has different entry.
[ WARN] [1506231691.013214891]: init: message from slugs, MSG-ID 192 ignored! Table has different entry.
[ WARN] [1506231691.013380307]: init: message from slugs, MSG-ID 193 ignored! Table has different entry.
[ WARN] [1506231691.013592912]: init: message from slugs, MSG-ID 194 ignored! Table has different entry.
[ INFO] [1506231691.018324214]: udp0: Bind address: 127.0.0.1:14560
[ INFO] [1506231691.019752912]: GCS bridge disabled
[ INFO] [1506231691.103731662]: udp0: Remote address: 127.0.0.1:39611
[ INFO] [1506231691.250676505]: Plugin 3dr_radio loaded
[ INFO] [1506231691.264047755]: Plugin 3dr_radio initialized
[ INFO] [1506231691.264570359]: Plugin actuator_control blacklisted
[ INFO] [1506231691.440133693]: Plugin adsb loaded
[ INFO] [1506231691.465375568]: Plugin adsb initialized
[ INFO] [1506231691.465918068]: Plugin altitude blacklisted
[ INFO] [1506231691.467175151]: Plugin cam_imu_sync loaded
[ INFO] [1506231691.472420932]: Plugin cam_imu_sync initialized
[ INFO] [1506231691.474178120]: Plugin command loaded
[ INFO] [1506231691.532675724]: Plugin command initialized
[ INFO] [1506231691.535164005]: Plugin distance_sensor loaded
[ INFO] [1506231691.643344266]: Plugin distance_sensor initialized
[ INFO] [1506231691.645563693]: Plugin fake_gps loaded
[ INFO] [1506231691.837523640]: Plugin fake_gps initialized
[ INFO] [1506231691.837783640]: Plugin ftp blacklisted
[ INFO] [1506231691.839559422]: Plugin global_position loaded
[ INFO] [1506231691.973624995]: Plugin global_position initialized
mavros_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:109: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = double; int Size = 4; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
================================================================================REQUIRED process [mavros-2] has died!
process has died [pid 6963, exit code -6, cmd /home/avionics/catkin_ws/devel/lib/mavros/mavros_node __name:=mavros __log:=/home/avionics/.ros/log/02c0d100-a0eb-11e7-b5ef-b827eb529962/mavros-2.log].
log file: /home/avionics/.ros/log/02c0d100-a0eb-11e7-b5ef-b827eb529962/mavros-2*.log
Initiating shutdown!
================================================================================
[mavros-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

### Diagnostics

```
avionics@avionics:~$ rostopic echo -n1 /diagnostics
WARNING: topic [/diagnostics] does not appear to be published yet
header: 
  seq: 0
  stamp: 
    secs: 1506231876
    nsecs: 885755601
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: Node starting up
    hardware_id: ''
    values: []
---

```

### Check ID
No output when problem occurs

**Comment by JMare** [comment]
Updates from debugging:

Problem seems to be in the HIL plugin, as it is reproducible with this pluginlists.yaml:
`plugin_blacklist: ['*'] plugin_whitelist: ['sys_*','hil']`

Have tried 0.21.0 and 0.21.2 and the problem occurs in both.

**Comment by TSC21** [comment]
@vooon is it possible that 13c92ad687bdc9dba96c4472bbb019d229b0556f is breaking this?

**Comment by TSC21** [comment]
@JMare I feel it weird that this comes from the HIL plugin. 13c92ad687bdc9dba96c4472bbb019d229b0556f only was inserted on 0.21.0. The HIL plugin does not change since 0.20.0 release, when it was inserted.

**Comment by vooon** [comment]
Does it work if you blacklist only hil?
It feels that problem not in one single plugin, rather than somewhere in common code.
And alignment is highly dependant on compiler version. Is that possible to use gcc 6.x?
Also weird idea - compile in Release mode, i want to know does deb's also broken or maybe not.

If problem in to_eigen() then unfortunately we should switch to another library, problem in RVO is unacceptable.

**Comment by TSC21** [comment]
> If problem in to_eigen() then unfortunately we should switch to another library, problem in RVO is unacceptable.

I don't think the problem is there. @JMare also tried 0.21.0 (which does not contain 13c92ad) with the same result.

**Comment by JMare** [comment]
It seems to work if I blacklist only HIL but I didn't run it enough times to say 100%.

On another note, I take it HIL=Hardware in the Loop?
HIL could be disabled by default for APM, since ardupilot dropped support for HIL some time ago.

**Comment by TSC21** [comment]
> On another note, I take it HIL=Hardware in the Loop?
HIL could be disabled by default for APM, since ardupilot dropped support for HIL some time ago.

It could but then we will be skipping the problem and not solving it.

**Comment by TSC21** [comment]
@JMare can you give us some insights on this? Does it keep happening on your side? I don't have a way of reproducing it unfortunately.

**Comment by JMare** [comment]
@TSC21 so far I have just been running with HIL blacklisted.
I will try again with latest master in the next few days and see if the problem still occurs with Raspberry Pi + APM.

**Comment by TSC21** [comment]
OK thank you @JMare

**Comment by jannsta1** [comment]
Hi, just to mention that I am setting up an MAV with raspberry pi 3 and pixhawk (using px4 flight stack) and encountered this issue. Blacklisting HIL in pluginlists.yaml also seems to prevent the segfault for my setup. Happy to provide any diagnostic info or test updated code if it helps.

**Comment by esaattia** [comment]
Hi,

I also am seeing seg fault on startup on the raspberry pi (Navio2) i am running ROS kinetic and was trying to run mavros 0.22 . the previos version 0.21 worked fine

**Comment by TSC21** [comment]
@vooon I guess the `to_eigen()` function is somewhat breaking this?

**Comment by TSC21** [comment]
@JMare @jannsta1 @esaattia can you try to revert the changes done in 13c92ad and check if that works to you?

**Comment by jannsta1** [comment]
@TSC21, I reverted to mavros 0.21.0 and still see the segfault (with the same traceback) with more or less the same frequency as 0.21.5. Once again blacklisting hil in px4_pluginlists.yaml more or less prevents the issue.

**Comment by TSC21** [comment]
> @TSC21, I reverted to mavros 0.21.0 and still see the segfault (with the same traceback) with more or less the same frequency as 0.21.5. Once again blacklisting hil in px4_pluginlists.yaml more or less prevents the issue.

Ok so something else is failing there. I need to take a look at the code to check what it can be.

**Comment by jannsta1** [comment]
Just a note to say this has now also happened a couple of times with hil blacklisted so I would guess a race condition of some sort that is made less likely when hil is enabled.

**Comment by JMare** [comment]
@TSC21 can hil be blacklisted by deafult in apm_pluginlists.yaml?
It won't fix this problem but there is no reason for HIL to run with APM.

I recently did another source install of mavros on Raspi3 and had the same problem with latest master, fixed by blacklisting HIL.

**Comment by TSC21** [comment]
> @TSC21 can hil be blacklisted by deafult in apm_pluginlists.yaml?
It won't fix this problem but there is no reason for HIL to run with APM.
>
>I recently did another source install of mavros on Raspi3 and had the same problem with latest master, fixed by blacklisting HIL.

Sure, please issue a PR when you have time.

**Comment by codingCoffee** [comment]
Has the issue been resolved? Blacklisting `hil` in `px4_pluginlists.yaml` does not solve the issue. Any leads on how to fix the problem? Trying on RPi4 

```
pi@raspberrypi:~/ros_catkin_ws $ roslaunch mavros apm.launch fcu_url:=/dev/ttyAMA0
... logging to /home/pi/.ros/log/cc6eafc6-bf23-11ec-9a31-dca63200a718/roslaunch-raspberrypi-24031.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://raspberrypi:45521/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_mav_type: ONBOARD_CONTROLLER
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/rangefinder_pub/field_of_view: 0.0
 * /mavros/distance_sensor/rangefinder_pub/frame_id: lidar
 * /mavros/distance_sensor/rangefinder_pub/id: 0
 * /mavros/distance_sensor/rangefinder_pub/send_tf: False
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/rangefinder_sub/id: 1
 * /mavros/distance_sensor/rangefinder_sub/orientation: PITCH_270
 * /mavros/distance_sensor/rangefinder_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_id: 4
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/horiz_accuracy: 0.5
 * /mavros/fake_gps/mocap_transform: False
 * /mavros/fake_gps/mocap_withcovariance: False
 * /mavros/fake_gps/satellites_visible: 6
 * /mavros/fake_gps/speed_accuracy: 0.0
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_hil_gps: True
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fake_gps/vert_accuracy: 0.5
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: /dev/ttyAMA0
 * /mavros/gcs_url:
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mission/use_mission_item_int: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/odometry/frame_tf/desired_frame: ned
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: map
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: map
 * /mavros/wheel_odometry/tf/send: True
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [24041]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to cc6eafc6-bf23-11ec-9a31-dca63200a718
process[rosout-1]: started with pid [24052]
started core service [/rosout]
process[mavros-2]: started with pid [24060]
[ INFO] [1650292105.320250811]: FCU URL: /dev/ttyAMA0
[ INFO] [1650292105.333873660]: serial0: device: /dev/ttyAMA0 @ 57600 bps
[ INFO] [1650292105.334899222]: GCS bridge disabled
[ INFO] [1650292105.377218568]: Plugin 3dr_radio loaded
[ INFO] [1650292105.382715784]: Plugin 3dr_radio initialized
[ INFO] [1650292105.383287167]: Plugin actuator_control blacklisted
[ INFO] [1650292105.408167002]: Plugin adsb loaded
[ INFO] [1650292105.417653545]: Plugin adsb initialized
[ INFO] [1650292105.418070614]: Plugin altitude blacklisted
[ INFO] [1650292105.419167991]: Plugin cam_imu_sync loaded
[ INFO] [1650292105.421642704]: Plugin cam_imu_sync initialized
[ INFO] [1650292105.422749618]: Plugin camera loaded
[ INFO] [1650292105.425315664]: Plugin camera initialized
[ INFO] [1650292105.426622945]: Plugin command loaded
[ INFO] [1650292105.449871428]: Plugin command initialized
[ INFO] [1650292105.451007879]: Plugin companion_process_status loaded
[ INFO] [1650292105.457835395]: Plugin companion_process_status initialized
[ INFO] [1650292105.458192132]: Plugin debug_value blacklisted
[ INFO] [1650292105.459367971]: Plugin distance_sensor loaded
mavros_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:109: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float; int Size = 4; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
================================================================================REQUIRED process [mavros-2] has died!
process has died [pid 24060, exit code -6, cmd /home/pi/ros_catkin_ws/devel/lib/mavros/mavros_node __name:=mavros __log:=/home/pi/.ros/log/cc6eafc6-bf23-11ec-9a31-dca63200a718/mavros-2.log].
log file: /home/pi/.ros/log/cc6eafc6-bf23-11ec-9a31-dca63200a718/mavros-2*.log
Initiating shutdown!
================================================================================
[mavros-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```
