### ISSUE TITLE
Fail to install Geographiclib dataset

### ISSUE THREAD

**Issue by Changliu52** [mavlink/mavros#963]
Hi,

I have had a couple of tries to reinstall mavros from source today (mavlink 2018.2.2-0, mavros 0.23.0).
However, when I run `install_geographiclib_datasets.sh`, it stated installing the datasets but only gives emply folder `/usr/local/share/GeographicLib/geoids`, `/usr/local/share/GeographicLib/gravity`, `/usr/local/share/GeographicLib/magnetic`,

Then, when I try to run `sudo geographiclib-get-geoids egm96-5`, it gives:
```
download egm96-5.tar.bz2 ...
--2018-03-03 11:58:48--  http://downloads.sourceforge.net/project/geographiclib/geoids-distrib/egm96-5.tar.bz2?use_mirror=autoselect
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 13.32.67.159, 13.32.67.197, 13.32.67.206, ...
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|13.32.67.159|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://downloads.sourceforge.net/#!/project/geographiclib/geoids-distrib/egm96-5.tar.bz2 [following]
--2018-03-03 11:58:48--  https://downloads.sourceforge.net/
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|13.32.67.159|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 652 [text/html]
Saving to: ‘/tmp/geoid-Nj9lOhZL/egm96-5.tar.bz2’

/tmp/geoid-Nj9lOhZL 100%[===================>]     652  --.-KB/s    in 0s      

2018-03-03 11:58:49 (16.9 MB/s) - ‘/tmp/geoid-Nj9lOhZL/egm96-5.tar.bz2’ saved [652/652]

unpack egm96-5.tar.bz2 ...
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

This looks like corrupted downloads. 
But I have tried multiple times, in different days, still the same error.
Not sure what else I can try?

Thanks in advance.
Chang

**Comment by TSC21** [comment]
I actually confirm this is happening also. This seems to be happening when the file is download with `wget`. A quick way around is to copy and paste https://downloads.sourceforge.net/#!/project/geographiclib/geoids-distrib/egm96-5.tar.bz2 to your browser, which automatically downloads the file, and then extract and copy the `geoids` folder to `/usr/share/GeographicLib`. I am going to check what may be the problem here.

**Comment by TSC21** [comment]
I think something may be wrong with the GeographicLib web platform, since I can't even access it - https://geographiclib.sourceforge.io/. It may be that it is down for a while and when it comes back up probably the script will work properly. @Changliu52 please follow the workaround above for now. As this is not related with MAVROS, I am closing.

**Comment by Changliu52** [comment]
Awesome. Thanks for the help Nuno.

**Comment by Pedro-Roque** [comment]
For me, I fixed related issues with geographiclib by installing it from source with cmake:
https://geographiclib.sourceforge.io/html/install.html#cmake

...and then installing geographiclib-tools from debian repo's . That fixed all dependencies

**Comment by TSC21** [comment]
@Pedro-Roque the problem is not the dependencies but actually the download of the datasets when using the `geographiclib-tools`.

**Comment by Pedro-Roque** [comment]
Should have read it slower! That might actually be their servers, just a matter of time until they fix it I guess

**Comment by karthikdesai** [comment]
Haha after 4 years, i am still facing this issue. It is as the problem is described. So weird

**Comment by Shahzaib210749** [comment]
i want to download egm96-5.tar.bz2 manually and have found many redirections like its say we start downloading in a while but not downloadin
![image](https://github.com/user-attachments/assets/60b308e8-9f5d-4098-955a-9ceadad4ab57)
![image_2024-09-07_171147377](https://github.com/user-attachments/assets/783b481a-58f1-4f23-a7f9-a727cee3e4ea)
g
